### ISSUE TITLE
Unity Project delay

### ISSUE THREAD

**Issue by kyh0214** [lihaowei1999/IRToolTrackingWithHololens2#5]
Thank you for the IR marker project!
These days, I'm used to having a hard time with this GitHub project.

And I want to know if your "Unity" project has the same problem as mine.
The problem is that clicking the Start Streaming button disables all Unity projects for about 1-3 minutes.
Do you have the same problem? Or what should I do about this problem?

Thank you again.

**Comment by lihaowei1999** [comment]
No, I have not met this problem. Are you running in editor? The streaming module is on-device only, so running in editor may possibly cause some problem. If you are looking for something for tracking, please look at the zmq branch.

The main branch is based on sensor data synchronization, which is strongly influenced by the router. I think others are providing methods to integrate the methods from this git to on device. I'm also using on-device tracking now instead of stream data and tracking.

**Comment by kyh0214** [comment]
Thanks for your advice! I struggled with this problem somedays.
But, I found the problem that was my python program..
This is caused from connection port.
I just wanna connect the "3001 port" to use only AHAT Camera From Hololens2.
Is there any method to remove another connection in python?
